server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    virtual-host: /theking
    host: 192.168.232.128
    username: theking
    password: 1217
  elasticsearch:
    rest:
      uris: http://192.168.232.128:9200
