server:
  port: 8093
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.232.128
  rabbitmq:
    host: 192.168.232.128
    port: 5672
    virtual-host: /theking
    username: theking
    password: 1217

jwt:
  token:
    pubKeyPath: C:\Users\saber\Desktop\shop\code\rsa\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key    #游客
    expireTime: 7776000
alipay:
  app_id: 2016101500692496
  notify_url: http://6f8y6kwili.52http.net/api/order/pay/success # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
