server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.232.128

jwt:
  token:
    pubKeyPath: C:\Users\saber\Desktop\shop\code\rsa\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key    #游客
    expireTime: 7776000
