server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

gmall:
  jwt:
    pubKeyPath: C:\Users\saber\Desktop\shop\code\rsa\rsa.pub # 公钥地址
    priKeyPath: C:\Users\saber\Desktop\shop\code\rsa\rsa.pri # 私钥地址
    secret: sf3423jsdf#3$@FDS32
    expire: 30 # 过期时间,单位分钟
    cookieName: GMALL_TOKEN