server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Theking1217.
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 192.168.232.128
    virtual-host: /theking
    username: theking
    password: 1217
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml  # 读取映射文件
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
