server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Theking1217.
  redis:
    host: 192.168.232.128
  rabbitmq:
    virtual-host: /theking #虚拟主机名称以/开头
    host: 192.168.232.128  #地址
    username: theking      #用户名
    password: 1217         #密码
mybatis-plus:
  mapper-locations: classpath:mapper/ums/*.xml  # 读取映射文件
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
